# Generated by Django 3.0.4 on 2020-03-22 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StateHolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mediaSharing', models.IntegerField(default=0)),
                ('homeEntertain', models.IntegerField(default=0)),
                ('peer2peer', models.IntegerField(default=0)),
                ('controlDegree', models.IntegerField(default=0)),
            ],
        ),
    ]
